POST http://127.0.0.1:5000/chatgpt/question?debug=true HTTP/1.1
content-type: application/json

{
    "question" : "Hello, who are you?"
}

POST http://127.0.0.1:5000/chatgpt/question?debug=true HTTP/1.1
content-type: application/json

{
    "question" : "What can you do?"
}


POST http://127.0.0.1:5000/chatgpt/question?debug=true HTTP/1.1
content-type: application/json

{
    "question" : "I really interest in Chinese art, please give me a tour",
    "position" : "(0.0,0.0,0.0)",
    "landmark" : ""
}

POST http://127.0.0.1:5000/chatgpt/question?debug=true HTTP/1.1
content-type: application/json

{
    "question" : "What is the most popular painting in this museum",
    "position" : "(0.0,0.0,0.0)",
    "landmark" : ""
}

POST http://127.0.0.1:5000/chatgpt/question?debug=true HTTP/1.1
content-type: application/json

{
    "question" : "Take me to this painting",
    "position" : "(0.0,0.0,0.0)",
    "landmark" : ""
}

Get http://127.0.0.1:5000/chatgpt/status HTTP/1.1